commands:
  NO_PLAYER: 'You can only use this command at console.'
  NO_CONSOLE: 'You must be a player to execute this command.'
  COMMAND_ERROR: 'An unknown error has occurred.'
  COMMAND_NUMBER: 'Expected a number, received string instead.'
  COMMAND_NO_PERMISSION: 'You do not have permission.'
potions:
  MILK_POTION_NAME: '&fSplash Potion of Milk'
  MILK_POTION_LORE:
    - '&cNegative Potion Effect Remover'
  MILK_POTION_RGB_COLOR:
    RED: 255
    GREEN: 255
    BLUE: 255
messages:
  TARGET_REMOVED_EFFECTS: '&cYour negative potion effects have been removed!'
  RECEIVE_POTION: '&eYou receive in your inventory a Milk potion'