commands:
  NO_PLAYER: 'You can only use this command at console.'
  NO_CONSOLE: 'You must be a player to execute this command.'
  COMMAND_ERROR: 'An unknown error has occurred.'
  COMMAND_NUMBER: 'Expected a number, received string instead.'
  COMMAND_NO_PERMISSION: 'You do not have permission.'
potions:
  MILK_POTION_NAME: '&fSplash Potion of Milk'
  MILK_POTION_LORE:
    - '&cNegative Potion Effect Remover'
  MILK_POTION_RGB_COLOR:
    RED: 255
    GREEN: 255
    BLUE: 255
messages:
  TARGET_REMOVED_EFFECTS: '&cYour potion effects have been removed!'
  TARGET_PREVENT_EFFECT: '&cA potion effect was prevented from being applied to you!'
  TARGET_REMOVED_BAD_EFFECTS: '&cYour negative potion effects have been removed!'
  TARGET_PREVENT_BAD_EFFECT: '&cA negative potion effect was prevented from being applied to you!'
  TIMER_MESSAGE: '&cYou are safe from all potion effects for the next %time% seconds!'
  TIMER_BAD_MESSAGE: '&cYou are safe from all bad potion effects for the next %time% seconds!'
  RECEIVE_POTION: '&eYou receive in your inventory a Milk potion'
options:
  REMOVE_ONLY_DEBUFF: true
  PROTECTION_TIMER: 15