name: MilkPotion
version: ${project.version}
main: es.minegold.milkpotion.MilkPotion
api-version: 1.13
authors: [ Teszeo, V1nc3ntWasTaken ]
description: Milk Splash Potion
website: https://crusade-craft.com
